jwt:
  secret: ThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExample
  #expiration: 86400000

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb  # H2 데이터베이스를 메모리 모드로 사용
    username: sa            # 기본 사용자 이름
    password:               # 비밀번호
  h2:
    console:
      enabled: true         # H2 콘솔을 사용할 수 있도록 활성화
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
    jpa:
      repositories:
        enabled: true

    redis:
      host: localhost
      port: 6379

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false

itemImgLocation: C:/shop/item
uploadPath: file:///C:/shop/