
server:
  port: 8888

jwt:
  secret: ThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExampleThisIsA_SecretKeyForJwtExample
  #expiration: 86400000

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: root
    password: 139500
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
    jpa:
      repositories:
        enabled: true

    redis:
      host: localhost
      port: 6379

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false

itemImgLocation: C:/shop/item

uploadPath: file:///C:/shop/